# .github/workflows/server-ci.yml
name: Server CI

on:
  push:
    branches: [master]
    paths:
      - 'server/**'
  pull_request:
    paths:
      - 'server/**'

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: server

    steps:
      - uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - run: bun install
      - run: bun run build